[project]
name = "goodganglabs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.1.0",
    "transformers>=4.57.1",
]

[tool.uv.workspace]
members = [
    "python3.11",
]
